modLoader="javafml" 
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Volwert123/More-Food-Forge/issues" 
[[mods]] 
modId="morefood" 
version="1.20.1-1.3.1"
displayName="More Food" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/more-food-xd"
logoFile="logo.png" 
authors="Volwert123, moritz_htk" 
description='''This Mod adds more food to Minecraft.'''
[[dependencies.morefood]] 
    modId="forge" 
    mandatory=true 
    versionRange="[47,)" 
    ordering="NONE"
     side="BOTH"
[[dependencies.morefood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
